#![cfg(feature = "serde")]
//! Read MATLAB MCOS opaque value classes from **genuine real-MATLAB `.mat`
//! v7.3 fixtures** and check the decoded values against an independent oracle.
//!
//! Every other opaque-read test in this crate round-trips against this crate's
//! own writer, which is circular: a bug shared by the writer and reader passes
//! unnoticed. These fixtures are different. They were produced by real MATLAB on
//! Windows (the userblock records `Platform: PCWIN64`) and are vendored from the
//! BSD-3 `foreverallama/matio` project under `tests/fixtures/mat_real/` (see the
//! `NOTICE.md` there for provenance). The expected values below are transcribed
//! from that project's MATLAB generator scripts (`tests/data/generators/*.m`)
//! and its independent pytest oracle (`tests/test_{datetime,duration,…}.py`),
//! so agreement here means the decoder matches MATLAB, not just itself.
//!
//! A note on `categorical` codes: MATLAB stores 1-based codes with `0` =
//! `<undefined>`, which is exactly [`MatCategorical::codes`]. The matio oracle
//! reports pandas codes, which are the same values shifted to 0-based with `-1`
//! for missing; the assertions below use MATLAB's 1-based convention.

use std::collections::HashMap;

use hdf5_pure::mat::{self, MatCategorical, MatDatetime, MatDuration};
use serde::Deserialize;

fn read<T: serde::de::DeserializeOwned>(name: &str) -> T {
    let path = format!("tests/fixtures/mat_real/{name}");
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    mat::from_bytes(&bytes).unwrap_or_else(|e| panic!("decode {path}: {e:?}"))
}

// ----------------------------------------------------------------------------
// datetime  (test_time_v73.mat, generated by test_times_gen.m)
// ----------------------------------------------------------------------------

#[derive(Deserialize)]
struct TimeFile {
    dt_basic: MatDatetime,
    dt_array: MatDatetime,
    dt_empty: MatDatetime,
    dt_fmt: MatDatetime,
    dt_tz: MatDatetime,
    dur_s: MatDuration,
    dur_m: MatDuration,
    dur_h: MatDuration,
    dur_days: MatDuration,
    dur_hms: MatDuration,
    dur_array: MatDuration,
    dur_empty: MatDuration,
    dur_years: MatDuration,
}

#[test]
fn datetime_decodes_against_real_matlab() {
    let t: TimeFile = read("test_time_v73.mat");

    // datetime(2025,4,1,12,0,0) -> 2025-04-01T12:00:00Z. Whole-second, so the
    // sub-millisecond part is exactly zero (this pins the millisecond epoch
    // scale against real MATLAB; the sub-ms scale needs a fractional fixture).
    assert_eq!(t.dt_basic.millis_utc, vec![1_743_508_800_000.0]);
    assert_eq!(t.dt_basic.sub_ms, vec![0.0]);

    // datetime(2025,4,1)+days(0:5) reshaped to 2x3, surfaced row-major flat.
    // (matio's numpy oracle: the same six instants, Apr 1/3/5 then Apr 2/4/6.)
    assert_eq!(
        t.dt_array.millis_utc,
        vec![
            1_743_465_600_000.0, // 2025-04-01
            1_743_638_400_000.0, // 2025-04-03
            1_743_811_200_000.0, // 2025-04-05
            1_743_552_000_000.0, // 2025-04-02
            1_743_724_800_000.0, // 2025-04-04
            1_743_897_600_000.0, // 2025-04-06
        ]
    );

    // datetime.empty -> no instants.
    assert!(t.dt_empty.millis_utc.is_empty());

    // The display format string round-trips; the instant is unchanged.
    assert_eq!(t.dt_fmt.fmt.as_deref(), Some("yyyy-MM-dd HH:mm:ss"));
    assert_eq!(t.dt_fmt.millis_utc, vec![1_743_508_800_000.0]);

    // Zoned datetime: the stored instant is UTC (noon America/New_York during
    // EDT == 16:00:00Z) and the zone name is carried as metadata. matio and
    // Julia's MAT.jl both DROP the zone here; this crate preserves it.
    assert_eq!(t.dt_tz.millis_utc, vec![1_743_523_200_000.0]);
    assert_eq!(t.dt_tz.tz.as_deref(), Some("America/New_York"));
}

#[test]
fn duration_decodes_against_real_matlab() {
    let t: TimeFile = read("test_time_v73.mat");

    // MATLAB stores durations as milliseconds.
    assert_eq!(t.dur_s.millis, vec![5_000.0]); // seconds(5)
    assert_eq!(t.dur_m.millis, vec![300_000.0]); // minutes(5)
    assert_eq!(t.dur_h.millis, vec![18_000_000.0]); // hours(5)
    assert_eq!(t.dur_days.millis, vec![432_000_000.0]); // days(5)
    assert_eq!(t.dur_hms.millis, vec![3_723_000.0]); // duration(1,2,3) = 1h2m3s

    // seconds([10 20 30; 40 50 60]) -> row-major flat.
    assert_eq!(
        t.dur_array.millis,
        vec![10_000.0, 20_000.0, 30_000.0, 40_000.0, 50_000.0, 60_000.0]
    );
    assert_eq!(
        t.dur_array.seconds(),
        vec![10.0, 20.0, 30.0, 40.0, 50.0, 60.0]
    );

    assert!(t.dur_empty.millis.is_empty()); // duration.empty

    // years([1 2 3]): MATLAB's calendar year is exactly 365.2425 days.
    let year_ms = 365.2425 * 86_400.0 * 1_000.0;
    assert_eq!(
        t.dur_years.millis,
        vec![year_ms, 2.0 * year_ms, 3.0 * year_ms]
    );
}

// ----------------------------------------------------------------------------
// categorical  (test_tables_v73.mat, generated by test_tables_gen.m)
// ----------------------------------------------------------------------------

#[derive(Deserialize)]
struct CatFile {
    cat_scalar: MatCategorical,
    cat_array: MatCategorical,
    cat_empty: MatCategorical,
    cat_from_numeric: MatCategorical,
    cat_unordered: MatCategorical,
    cat_ordered: MatCategorical,
    cat_missing: MatCategorical,
    cat_mixed_case: MatCategorical,
    cat_string: MatCategorical,
    #[serde(rename = "cat_3D")]
    cat_3d: MatCategorical,
}

#[test]
fn categorical_decodes_against_real_matlab() {
    // The tables fixture also holds many `table`/`timetable` variables; serde
    // skips them (they decode losslessly as opaque maps), exercising that the
    // whole-file read survives undecoded-but-valid opaque neighbors.
    let c: CatFile = read("test_tables_v73.mat");

    // categorical({'red','green','blue','red'}); categories sort to b/g/r.
    assert_eq!(c.cat_scalar.codes, vec![3, 2, 1, 3]);
    assert_eq!(c.cat_scalar.categories, ["blue", "green", "red"]);
    assert!(!c.cat_scalar.is_ordinal);
    assert_eq!(
        c.cat_scalar.labels(),
        vec![
            Some("red".into()),
            Some("green".into()),
            Some("blue".into()),
            Some("red".into()),
        ]
    );

    // 2x2 categorical -> codes surface row-major flat.
    assert_eq!(c.cat_array.codes, vec![2, 3, 1, 2]);
    assert_eq!(c.cat_array.categories, ["high", "low", "medium"]);

    // categorical({}) -> empty: real MATLAB stores NO properties for this
    // object, so the decoder must treat absent `codes` as an empty categorical
    // rather than erroring (which previously aborted the whole-file read).
    assert!(c.cat_empty.codes.is_empty());
    assert!(c.cat_empty.categories.is_empty());

    // categorical([1 2 3 2 1], [1 2 3], {'low','medium','high'}) keeps the
    // caller-specified (unsorted) category order.
    assert_eq!(c.cat_from_numeric.codes, vec![1, 2, 3, 2, 1]);
    assert_eq!(c.cat_from_numeric.categories, ["low", "medium", "high"]);

    // Explicit value-set order is preserved (cold/warm/hot, not sorted).
    assert_eq!(c.cat_unordered.codes, vec![1, 3, 2]);
    assert_eq!(c.cat_unordered.categories, ["cold", "warm", "hot"]);
    assert!(!c.cat_unordered.is_ordinal);

    // Ordinal categorical carries both flags.
    assert_eq!(c.cat_ordered.codes, vec![1, 2, 3]);
    assert_eq!(c.cat_ordered.categories, ["small", "medium", "large"]);
    assert!(c.cat_ordered.is_ordinal);
    assert!(c.cat_ordered.is_protected);

    // Missing element ('' input) -> code 0 = <undefined>.
    assert_eq!(c.cat_missing.codes, vec![1, 0, 2, 3]);
    assert_eq!(c.cat_missing.categories, ["cat", "dog", "mouse"]);
    assert_eq!(c.cat_missing.labels()[1], None);

    // Case-sensitive, sorted by MATLAB's ordering.
    assert_eq!(c.cat_mixed_case.codes, vec![3, 4, 1, 2, 5]);
    assert_eq!(
        c.cat_mixed_case.categories,
        ["OFF", "ON", "On", "off", "on"]
    );

    // Categories created from a MATLAB string array.
    assert_eq!(c.cat_string.codes, vec![2, 3, 1, 4]);
    assert_eq!(
        c.cat_string.categories,
        ["autumn", "spring", "summer", "winter"]
    );

    // 3-D categorical -> codes flatten row-major over all 2x3x2 elements.
    assert_eq!(c.cat_3d.codes, vec![3, 3, 2, 2, 1, 1, 3, 3, 2, 2, 1, 1]);
    assert_eq!(c.cat_3d.categories, ["maybe", "no", "yes"]);
}

// ----------------------------------------------------------------------------
// string  (test_string_v73.mat, generated by test_string_gen.m)
// ----------------------------------------------------------------------------

#[derive(Deserialize)]
struct StringFile {
    string_scalar: String,
    string_array: Vec<String>,
    string_empty: String,
}

#[test]
fn string_decodes_against_real_matlab() {
    let s: StringFile = read("test_string_v73.mat");
    assert_eq!(s.string_scalar, "Hello");
    assert_eq!(s.string_empty, "");
    // ["Apple","Banana","Cherry"; "Date","Fig","Grapes"] surfaced column-major
    // (MATLAB storage order), matching matio's flattened layout.
    assert_eq!(
        s.string_array,
        ["Apple", "Date", "Banana", "Fig", "Cherry", "Grapes"]
    );
}

// ----------------------------------------------------------------------------
// datetime sub-millisecond scale  (matjl_struct_table_datetime.mat, MAT.jl)
// ----------------------------------------------------------------------------

#[derive(Deserialize)]
struct DtComplexFile {
    s: DtComplexInner,
}

#[derive(Deserialize)]
struct DtComplexInner {
    #[serde(rename = "testDatetime")]
    test_datetime: MatDatetime,
    #[serde(rename = "testDatetimeComplex")]
    test_datetime_complex: MatDatetime,
}

#[test]
fn datetime_subms_double_double_against_real_matlab() {
    // This MAT.jl fixture is real MATLAB output whose `testDatetimeComplex` has
    // a non-zero imaginary part, stored as an HDF5 version-1 compound
    // {real, imag} of f64. It pins the sub-millisecond scale: MATLAB's datetime
    // is a "double-double" where the true millisecond value is
    // `millis_utc + sub_ms`, with `sub_ms` an ADDITIVE residual in
    // MILLISECONDS (below the high part's ULP) — not a microsecond field.
    let f: DtComplexFile = read("matjl_struct_table_datetime.mat");

    // Whole-millisecond datetime: the imaginary residual is exactly zero.
    assert_eq!(f.s.test_datetime.millis_utc, vec![1_575_304_969_634.0]);
    assert_eq!(f.s.test_datetime.sub_ms, vec![0.0]);

    // Sub-millisecond datetime: the high part carries the fractional millisecond
    // (…868.83) and the low part is the tiny residual. Exact bytes MATLAB wrote.
    let dtc = &f.s.test_datetime_complex;
    assert_eq!(dtc.millis_utc, vec![1_765_052_919_868.83]);
    assert_eq!(dtc.sub_ms, vec![-7.812_678_813_934_326e-5]);

    // The residual is a genuine sub-millisecond quantity (here ~8e-5 ms): if the
    // imaginary part were a microsecond-scaled field it could not be this small
    // relative to the high part. Confirms the additive-millisecond reading.
    assert!(dtc.sub_ms[0] != 0.0 && dtc.sub_ms[0].abs() < 1e-3);

    // nanoseconds() preserves the high part's fractional-ms precision; the
    // residual is below f64 ULP at this epoch and does not survive (documented).
    assert_eq!(dtc.nanoseconds(), vec![1_765_052_919_868.83 * 1e6]);
}

// ----------------------------------------------------------------------------
// robustness: malformed real-MATLAB subsystems are handled without panicking
// ----------------------------------------------------------------------------

#[test]
fn malformed_mcos_is_handled_without_panicking() {
    // Deliberately damaged real-MATLAB subsystems. The invariant is that the
    // reader never panics on them. The fixture with an out-of-range object id
    // surfaces a typed error; the other's damage is tolerated and its variable
    // still decodes (as matio also reads it). Both complete without panicking.
    let meta =
        std::fs::read("tests/fixtures/mat_real/test_corrupted_mcos_object_metadata.mat").unwrap();
    assert!(mat::from_bytes::<HashMap<String, serde_json::Value>>(&meta).is_err());

    let subsys = std::fs::read("tests/fixtures/mat_real/test_corrupted_subsystem.mat").unwrap();
    // Tolerated by our parser; must return (Ok or Err) rather than panic.
    let _ = mat::from_bytes::<HashMap<String, serde_json::Value>>(&subsys);
}
